server:
  port: 8222

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ordersdb
    username: sa
    password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true

